In [3]:
import pandas as pd

train_df=pd.read_csv(r"/Users/suriya/Ukesh_AIML_Projects/Deep_Learning_Comment_Toxicity/Data/train.csv")
train_df.head(15)

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate
0,0000997932d777bf,Explanation\nWhy the edits made under my usern...,0,0,0,0,0,0
1,000103f0d9cfb60f,D'aww! He matches this background colour I'm s...,0,0,0,0,0,0
2,000113f07ec002fd,"Hey man, I'm really not trying to edit war. It...",0,0,0,0,0,0
3,0001b41b1c6bb37e,"""\nMore\nI can't make any real suggestions on ...",0,0,0,0,0,0
4,0001d958c54c6e35,"You, sir, are my hero. Any chance you remember...",0,0,0,0,0,0
5,00025465d4725e87,"""\n\nCongratulations from me as well, use the ...",0,0,0,0,0,0
6,0002bcb3da6cb337,COCKSUCKER BEFORE YOU PISS AROUND ON MY WORK,1,1,1,0,1,0
7,00031b1e95af7921,Your vandalism to the Matt Shirvington article...,0,0,0,0,0,0
8,00037261f536c51d,Sorry if the word 'nonsense' was offensive to ...,0,0,0,0,0,0
9,00040093b2687caa,alignment on this subject and which are contra...,0,0,0,0,0,0
10,0005300084f90edc,"""\nFair use rationale for Image:Wonju.jpg\n\nT...",0,0,0,0,0,0
11,00054a5e18b50dd4,bbq \n\nbe a man and lets discuss it-maybe ove...,0,0,0,0,0,0
12,0005c987bdfc9d4b,Hey... what is it..\n@ | talk .\nWhat is it......,1,0,0,0,0,0
13,0006f16e4e9f292e,Before you start throwing accusations and warn...,0,0,0,0,0,0
14,00070ef96486d6f9,"Oh, and the girl above started her arguments w...",0,0,0,0,0,0

In [37]:
train_df.columns

Index(['id', 'comment_text', 'toxic', 'severe_toxic', 'obscene', 'threat',
       'insult', 'identity_hate', 'char_count', 'word_count',
       'sentence_count'],
      dtype='object')

In [2]:
train_df.shape

(159571, 8)

In [3]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159571 entries, 0 to 159570
Data columns (total 8 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   id             159571 non-null  object
 1   comment_text   159571 non-null  object
 2   toxic          159571 non-null  int64
 3   severe_toxic   159571 non-null  int64
 4   obscene        159571 non-null  int64
 5   threat         159571 non-null  int64
 6   insult         159571 non-null  int64
 7   identity_hate  159571 non-null  int64
dtypes: int64(6), object(2)
memory usage: 9.7+ MB

In [4]:
train_df.isna().sum()

id               0
comment_text     0
toxic            0
severe_toxic     0
obscene          0
threat           0
insult           0
identity_hate    0
dtype: int64

In [5]:
train_df.duplicated().sum()

np.int64(0)

In [41]:
labels=['toxic', 'severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate']

for lab in labels:
    print(train_df[lab].value_counts())

toxic
0    144277
1     15294
Name: count, dtype: int64
severe_toxic
0    157976
1      1595
Name: count, dtype: int64
obscene
0    151122
1      8449
Name: count, dtype: int64
threat
0    159093
1       478
Name: count, dtype: int64
insult
0    151694
1      7877
Name: count, dtype: int64
identity_hate
0    158166
1      1405
Name: count, dtype: int64

In [6]:
pd.set_option("display.max_colwidth",None)

train_df['comment_text'].sample(10)

108818                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Hello this is cheese....
129823                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         No way, I'm sticking to this one.  Go ahead and block and see what happens.  Everything I said re the other affair was proved and admitted privately by Arbcom.
51887                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Carmicheal was a member of the Black Panther Party and became a black separatist, I am only adding information listed in his biography so please don't revert it again, unless you change his biography as well
147177                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             I did, these people are from the modern state of India.   PacificWarrior101
12560                                                                                                                                                                               "\n\n\n\nThe terms ""folk dance"" and ""vernacular dance"", objectively, mean the same thing. IMHO, either is ""correct"" as a description of Lindy Hop. However, ""vernacular jazz dance"" is, in my experience, the label Lindy dancers and scholars choose to apply. Lindy is a ""jazz dance"" in the sense of Marshall & Jean Stearns' book Jazz Dance: The Story of American Vernacular Dance (a sense that is not well-reflected in the current ""Jazz Dance"" article on Wikipedia).  - szarka\n\n"
144336                                                                                                                                                                                                                                                               There is more to this than one version or another - there have been collective and group ceremonies since 1983 - I think any one source or authority might be insufficient to explain the issue - also there was the question as to whether prior to the re-building and renovation as to whether any practitioners of any belief actually had used the site for any form of religious practice at all for centuries Suro
118591                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 "\n\n Please do not vandalize pages, as you did with this edit to Cod. If you continue to do so, you will be blocked from editing.    "
141470    "  (As for Jeppiz, again, your behavior was arguably rude and appalling and dismissive and ignorant (by your own admission) and ""I don't like"" and not acknowledging the quoted WP guideline of ""minority view"" given SOME mention, but just ""not as much"", etc etc. I'm not perfect, and neither are you, if that's the case.  And also the ""modify instead of revert"" etc..   And you lied about my ignoring ""Bold, Revert, Discuss"", as that's all I've been doing here, for hours, on this talk page, which you show no respect or appreciation for.  So as I said, you're very pot-kettle-black...though I tried to discuss and present and work here with you.)    "
142925                                                                                                                                                                                                                                                                                                                           Thank you Osli. Dear Ilir, can you please inform us which one has your preference? It is really time to lift the editing block on the article. Once you have stated your preference, I will inform the editor who blocked the article and change the text to the version you choose (of the 5 options above), because both Osli and I agree to all 5 of them.
11073                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      I really dont care\n\nNo i dont, you sad little man
Name: comment_text, dtype: object

In [7]:
train_df["word_count"]=train_df["comment_text"].str.split().str.len()
train_df.head(20)

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate,word_count
0,0000997932d777bf,"Explanation\nWhy the edits made under my username Hardcore Metallica Fan were reverted? They weren't vandalisms, just closure on some GAs after I voted at New York Dolls FAC. And please don't remove the template from the talk page since I'm retired now.89.205.38.27",0,0,0,0,0,0,43
1,000103f0d9cfb60f,"D'aww! He matches this background colour I'm seemingly stuck with. Thanks. (talk) 21:51, January 11, 2016 (UTC)",0,0,0,0,0,0,17
2,000113f07ec002fd,"Hey man, I'm really not trying to edit war. It's just that this guy is constantly removing relevant information and talking to me through edits instead of my talk page. He seems to care more about the formatting than the actual info.",0,0,0,0,0,0,42
3,0001b41b1c6bb37e,"""\nMore\nI can't make any real suggestions on improvement - I wondered if the section statistics should be later on, or a subsection of """"types of accidents"""" -I think the references may need tidying so that they are all in the exact same format ie date format etc. I can do that later on, if no-one else does first - if you have any preferences for formatting style on references or want to do it yourself please let me know.\n\nThere appears to be a backlog on articles for review so I guess there may be a delay until a reviewer turns up. It's listed in the relevant form eg Wikipedia:Good_article_nominations#Transport """,0,0,0,0,0,0,113
4,0001d958c54c6e35,"You, sir, are my hero. Any chance you remember what page that's on?",0,0,0,0,0,0,13
5,00025465d4725e87,"""\n\nCongratulations from me as well, use the tools well. · talk """,0,0,0,0,0,0,13
6,0002bcb3da6cb337,COCKSUCKER BEFORE YOU PISS AROUND ON MY WORK,1,1,1,0,1,0,8
7,00031b1e95af7921,"Your vandalism to the Matt Shirvington article has been reverted. Please don't do it again, or you will be banned.",0,0,0,0,0,0,20
8,00037261f536c51d,"Sorry if the word 'nonsense' was offensive to you. Anyway, I'm not intending to write anything in the article(wow they would jump on me for vandalism), I'm merely requesting that it be more encyclopedic so one can use it for school as a reference. I have been to the selective breeding page but it's almost a stub. It points to 'animal breeding' which is a short messy article that gives you no info. There must be someone around with expertise in eugenics? 93.161.107.169",0,0,0,0,0,0,83
9,00040093b2687caa,alignment on this subject and which are contrary to those of DuLithgow,0,0,0,0,0,0,12
10,0005300084f90edc,"""\nFair use rationale for Image:Wonju.jpg\n\nThanks for uploading Image:Wonju.jpg. I notice the image page specifies that the image is being used under fair use but there is no explanation or rationale as to why its use in Wikipedia articles constitutes fair use. In addition to the boilerplate fair use template, you must also write out on the image description page a specific explanation or rationale for why using this image in each article is consistent with fair use.\n\nPlease go to the image description page and edit it to include a fair use rationale.\n\nIf you have uploaded other fair use media, consider checking that you have specified the fair use rationale on those pages too. You can find a list of 'image' pages you have edited by clicking on the """"my contributions"""" link (it is located at the very top of any Wikipedia page when you are logged in), and then selecting """"Image"""" from the dropdown box. Note that any fair use images uploaded after 4 May, 2006, and lacking such an explanation will be deleted one week after they have been uploaded, as described on criteria for speedy deletion. If you have any questions please ask them at the Media copyright questions page. Thank you. (talk • contribs • ) \nUnspecified source for Image:Wonju.jpg\n\nThanks for uploading Image:Wonju.jpg. I noticed that the file's description page currently doesn't specify who created the content, so the copyright status is unclear. If you did not create this file yourself, then you will need to specify the owner of the copyright. If you obtained it from a website, then a link to the website from which it was taken, together with a restatement of that website's terms of use of its content, is usually sufficient information. However, if the copyright holder is different from the website's publisher, then their copyright should also be acknowledged.\n\nAs well as adding the source, please add a proper copyright licensing tag if the file doesn't have one already. If you created/took the picture, audio, or video then the tag can be used to release it under the GFDL. If you believe the media meets the criteria at Wikipedia:Fair use, use a tag such as or one of the other tags listed at Wikipedia:Image copyright tags#Fair use. See Wikipedia:Image copyright tags for the full list of copyright tags that you can use.\n\nIf you have uploaded other files, consider checking that you have specified their source and tagged them, too. You can find a list of files you have uploaded by following [ this link]. Unsourced and untagged images may be deleted one week after they have been tagged, as described on criteria for speedy deletion. If the image is copyrighted under a non-free license (per Wikipedia:Fair use) then the image will be deleted 48 hours after . If you have any questions please ask them at the Media copyright questions page. Thank you. (talk • contribs • ) """,0,0,0,0,0,0,494
11,00054a5e18b50dd4,bbq \n\nbe a man and lets discuss it-maybe over the phone?,0,0,0,0,0,0,11
12,0005c987bdfc9d4b,"Hey... what is it..\n@ | talk .\nWhat is it... an exclusive group of some WP TALIBANS...who are good at destroying, self-appointed purist who GANG UP any one who asks them questions abt their ANTI-SOCIAL and DESTRUCTIVE (non)-contribution at WP?\n\nAsk Sityush to clean up his behavior than issue me nonsensical warnings...",1,0,0,0,0,0,53
13,0006f16e4e9f292e,"Before you start throwing accusations and warnings at me, lets review the edit itself-making ad hominem attacks isn't going to strengthen your argument, it will merely make it look like you are abusing your power as an admin. \nNow, the edit itself is relevant-this is probably the single most talked about event int he news as of late. His absence is notable, since he is the only living ex-president who did not attend. That's certainly more notable than his dedicating an aircracft carrier. \nI intend to revert this edit, in hopes of attracting the attention of an admin that is willing to look at the issue itself, and not throw accusations around quite so liberally. Perhaps, if you achieve a level of civility where you can do this, we can have a rational discussion on the topic and resolve the matter peacefully.",0,0,0,0,0,0,142
14,00070ef96486d6f9,"Oh, and the girl above started her arguments with me. She stuck her nose where it doesn't belong. I believe the argument was between me and Yvesnimmo. But like I said, the situation was settled and I apologized. Thanks,",0,0,0,0,0,0,39
15,00078f8ce7eb276d,"""\n\nJuelz Santanas Age\n\nIn 2002, Juelz Santana was 18 years old, then came February 18th, which makes Juelz turn 19 making songs with The Diplomats. The third neff to be signed to Cam's label under Roc A Fella. In 2003, he was 20 years old coming out with his own singles """"Santana's Town"""" and """"Down"""". So yes, he is born in 1983. He really is, how could he be older then Lloyd Banks? And how could he be 22 when his birthday passed? The homie neff is 23 years old. 1983 - 2006 (Juelz death, god forbid if your thinking about that) equals 23. Go to your caculator and stop changing his year of birth. My god.""",0,0,0,0,0,0,118
16,0007e25b2121310b,"Bye! \n\nDon't look, come or think of comming back! Tosser.",1,0,0,0,0,0,10
17,000897889268bc93,REDIRECT Talk:Voydan Pop Georgiev- Chernodrinski,0,0,0,0,0,0,5
18,0009801bd85e5806,The Mitsurugi point made no sense - why not argue to include Hindi on Ryo Sakazaki's page to include more information?,0,0,0,0,0,0,21
19,0009eaea3325de8c,"Don't mean to bother you \n\nI see that you're writing something regarding removing anything posted here and if you do oh well but if not and you can acctually discuss this with me then even better.\n\nI'd like to ask you to take a closer look at the Premature wrestling deaths catagory and the men listed in it, surely these men belong together in some catagory. Is there anything that you think we can do with the catagory besides delting it?",0,0,0,0,0,0,81

In [24]:
(train_df["comment_text"].str.strip() == "").sum()

np.int64(0)

In [26]:
train_df["comment_text"].str.contains("www", case=False).sum()

np.int64(2750)

In [30]:
train_df["comment_text"].str.contains("http", case=False).sum()

np.int64(4804)

In [31]:
train_df["comment_text"].str.contains("<", regex=False).sum()

np.int64(370)

In [32]:
train_df["comment_text"].str.contains(r"\d", regex=True).sum()

np.int64(51212)

In [50]:
train_df[train_df["toxic"]==1]['comment_text'].head()

6                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               COCKSUCKER BEFORE YOU PISS AROUND ON MY WORK
12                                                                                                                                                                                                                                                                                                                                                       Hey... what is it..\n@ | talk .\nWhat is it... an exclusive group of some WP TALIBANS...who are good at destroying, self-appointed purist who GANG UP any one who asks them questions abt their ANTI-SOCIAL and DESTRUCTIVE (non)-contribution at WP?\n\nAsk Sityush to clean up his behavior than issue me nonsensical warnings...
16                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               Bye! \n\nDon't look, come or think of comming back! Tosser.
42    You are gay or antisemmitian? \n\nArchangel WHite Tiger\n\nMeow! Greetingshhh!\n\nUh, there are two ways, why you do erased my comment about WW2, that holocaust was brutally slaying of Jews and not gays/Gypsys/Slavs/anyone...\n\n1 - If you are anti-semitian, than shave your head bald and go to the skinhead meetings!\n\n2 - If you doubt words of the Bible, that homosexuality is a deadly sin, make a pentagram tatoo on your forehead go to the satanistic masses with your gay pals!\n\n3 - First and last warning, you fucking gay - I won't appreciate if any more nazi shwain would write in my page! I don't wish to talk to you anymore!\n\nBeware of the Dark Side!
43                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  FUCK YOUR FILTHY MOTHER IN THE ASS, DRY!
Name: comment_text, dtype: object

In [51]:
train_df[train_df["toxic"]==0]['comment_text'].head()

0                                                                                                                                                                                                                                                                                                                                                                             Explanation\nWhy the edits made under my username Hardcore Metallica Fan were reverted? They weren't vandalisms, just closure on some GAs after I voted at New York Dolls FAC. And please don't remove the template from the talk page since I'm retired now.89.205.38.27
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      D'aww! He matches this background colour I'm seemingly stuck with. Thanks.  (talk) 21:51, January 11, 2016 (UTC)
2                                                                                                                                                                                                                                                                                                                                                                                                             Hey man, I'm really not trying to edit war. It's just that this guy is constantly removing relevant information and talking to me through edits instead of my talk page. He seems to care more about the formatting than the actual info.
3    "\nMore\nI can't make any real suggestions on improvement - I wondered if the section statistics should be later on, or a subsection of ""types of accidents""  -I think the references may need tidying so that they are all in the exact same format ie date format etc. I can do that later on, if no-one else does first - if you have any preferences for formatting style on references or want to do it yourself please let me know.\n\nThere appears to be a backlog on articles for review so I guess there may be a delay until a reviewer turns up. It's listed in the relevant form eg Wikipedia:Good_article_nominations#Transport  "
4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   You, sir, are my hero. Any chance you remember what page that's on?
Name: comment_text, dtype: object